# Generated by Django 3.2.6 on 2021-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_ripeness',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_ripe',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
